[supervisord]
nodaemon=true

[program:backend]
command=uvicorn app.backend.web_rag_api:app --host 0.0.0.0 --port 9999
autostart=true
autorestart=true

[program:frontend]
command=/bin/bash -c "sleep 4 && streamlit run app/frontend/index.py --server.address=0.0.0.0 --server.port=8501"
autostart=true
autorestart=true